source 'https://rubygems.org'
ruby '2.0.0'
gem 'rails', '4.1.6'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'spring',        group: :development
gem 'devise'
gem 'devise_invitable'
gem 'haml-rails'
gem 'paperclip', '3.5.3'
gem 'simple_xlsx_reader'
gem 'spreadsheet'
gem 'semantic-ui-sass', github: 'doabit/semantic-ui-sass', branch: 'v1.0beta'
gem 'rails-timeago', '~> 2.0'
gem 'kaminari'
gem 'wiselinks'
gem 'cancan'
gem 'annotate'
gem 'scoped_search'
gem 'httparty'
gem 'acts_as_tenant'
gem 'chartkick'
gem 'groupdate'
gem 'letter_opener'
gem 'jquery-infinite-pages'
gem 'newrelic_rpm'
gem 'rollbar'
gem 'mysql2', '0.3.15'
gem 'font-awesome-sass'
gem 'rufus-scheduler'

gem 'sidekiq', '3.2.5'
gem 'sinatra'
gem 'sidetiq'
group :development do
  gem 'better_errors'
  gem 'binding_of_caller', :platforms=>[:mri_20]
  gem 'html2haml'
  gem 'quiet_assets'
  gem 'rails_layout'
end
group :development, :test do
  gem 'pry-rails'
  gem 'pry-rescue'
  gem 'rubocop'
end
