# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24655eb02f42412e906c5f81ed70882f2d021c551c134d91c18b8d78b4fa3b2adbd2b77b4180048f82494cf8620092f477eba31cb4116c1362787eca4b5dc57d

test:
  secret_key_base: bf1b5ccc07fa07e45c372cfec2950e4c8c490e38fd50169b8798d3bc09c7f561c890aeb6cd318db4e1656293b214b33f03ae9f4fb3a5681644ff0548fd9189ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
